name: Release

on:
  release:
    types: [published]

env:
  CARGO_TERM_COLOR: always

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Compile and release
      uses: rust-build/rust-build.action@v1.4.5
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        PRE_BUILD: pre-build.sh
        RUSTTARGET: x86_64-unknown-linux-musl
        TOOLCHAIN_VERSION: stable
        EXTRA_FILES: "README.md LICENSE"
